function InfoDisp()
% Function InfoDisp
%   Display some general informations of this code
%================================================================================

disp('This program is to regularize the randomly distributed seismic stations onto a perfect grid. Both the input and the output are in SAC format. The regularization can greatly reduce the artifacts caused by uneven stations intervals, and can avoid the step effect due to insufficient station numbers. Both the theory and application examples can be found in our paper. This code was firstly finished by Jinhai Zhang, Aug 2013, and modified by Chengliang Xie, June 2020. This code can be freely used for personal and non-commercial purpose.')
disp(' ')

disp('Please send emails to authors for either comments or bugs.')
disp(' ')
disp('----------------------------------------------')
disp(' Dr. JinHai Zhang')
disp(' No.19, Beitucheng Western Road')
disp(' Institute of Geology and Geophysics')
disp(' Chinese Academy of Sciences')
disp(' Beijing, 100029')
disp(' CHINA')
disp(' ')
disp(' Phone:')
disp('   +86-10-82998440(Office)')
disp(' E-mail: ')
disp('   zjh@mail.iggcas.ac.cn')
disp('   geophysics.zhang@gmail.com')
disp(' Homepage:')
disp('   http://people.gucas.ac.cn/~zjh?language=en')
disp('----------------------------------------------')
disp(' ')
disp(' Dr. Chengliang Xie')
disp(' No. 29, Xueyuan Road')
disp(' China University of Geosciences, Beijing')
disp(' Beijing, 100083')
disp(' CHINA')
disp(' ')
disp(' Phone:')
disp('   +86-15201018722')
disp(' E-mail: ')
disp('   clx@cugb.edu.cn')
disp('----------------------------------------------')
disp(' ')
